version: '3'

services:

  devdash-mysql:
    image: mysql:8.0
    networks: 
      - devdash_net
    environment:
      - MYSQL_ROOT_PASSWORD=Monkey2020
      - MYSQL_DATABASE=tutorial
      - MYSQL_USER=dduser
      - MYSQL_PASSWORD=Monkey2020
    ports:
      - 3306:3306
    volumes:
      - myappdd:/var/lib/mysql

  devdash-be:
    image: dev_dash
    networks: 
      - devdash_net
    depends_on:
      - devdash-mysql
    ports:
      - 8080:8080
    environment:
      - db.driver=com.mysql.jdbc.Driver
      - db.url=jdbc:mysql://devdash-mysql:3306/tutorial?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - db.username=root
      - db.password=Monkey2020
      - SPRING_DATASOURCE_URL=jdbc:mysql://devdash-mysql:3306/tutorial?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Monkey2020
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

networks: 
  devdash_net:

volumes:
  myappdd: