version: '3'

services:

  devdash-ui:
    image: dev_dash_ui
    networks: 
      - devdash_net
    ports:
      - 8682:80

  devdash-mysql:
    image: mysql:8.0
    networks: 
      - devdash_net
    environment:
      - MYSQL_ROOT_PASSWORD=Monkey2020
      - MYSQL_DATABASE=dddatabase
      - MYSQL_USER=dduser
      - MYSQL_PASSWORD=Monkey2020
    ports:
      - 3306:3306
    volumes:
      - ddmysql:/var/lib/mysql

  devdash-be:
    image: dev_dash_be
    networks: 
      - devdash_net
    depends_on:
      - devdash-mysql
      - devdash-ui
    ports:
      - 8683:8683
    environment:
      - db.driver=com.mysql.jdbc.Driver
      - db.url=jdbc:mysql://devdash-mysql:3306/dddatabase?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - db.username=dduser
      - db.password=Monkey2020

networks: 
  devdash_net:

volumes:
  ddmysql:
